### ISSUE TITLE
2.4.0 - Typescript: Property 'handle' does not exist on type 'AdyenComponent'

### ISSUE THREAD

**Issue by zegenerative** [Adyen/adyen-react-native#534] opened 2024-09-30 13:39 UTC
**Describe the bug**
AdyenCheckout onSubmit callback expects a second argument 'component' typed as AdyenComponent, but the component needs to be able to handle additional action, which seems only to be present in `AdyenActionComponent`

**Comment by descorp** [comment] 2024-10-01 14:40
Hey @zegenerative 

This was done on purpose, since not every component is capable of handling actions or not in every case it is needed.
However, you are right that `AdyenComponent` is limiting, and we can ignore Interface Segregation Principle here for the general convenience 🤔

**Comment by descorp** [comment] 2024-10-04 13:58
Improved!
#540 

Thanks for feedback 💚

**Comment by zegenerative** [comment] 2024-10-08 07:35
@descorp thanks! when will this be released?

**Comment by descorp** [comment] 2024-10-08 12:04
Hey @zegenerative 

Since this is not a blocking issue, we will release this at 2.5.0. ETA end of October.

**Comment by gunnartorfis** [comment] 2024-12-07 08:48
@descorp FYI this is still an issue in 2.4.1.

**Comment by camil-adyen** [comment] 2024-12-10 15:51
HI @gunnartorfis, can you please confirm that the issue has been resolved in our [latest release](https://github.com/Adyen/adyen-react-native/releases/tag/2.5.0)?

**Comment by irawel** [comment] 2024-12-26 15:11
Hi @camil-adyen, I can confirm that this has been fixed on the release 2.5.0.

**Closed as completed** 2024-12-27 10:20 UTC
Labels: enhancement, to be released
