### ISSUE TITLE
Loading overlay not closing

### ISSUE THREAD

**Issue by pinpong** [Adyen/adyen-react-native#188] opened 2023-04-14 06:43 UTC
**Describe the bug**
Loading overlay is still visible after closing the webview

**To Reproduce**
1. run the example [PR](https://github.com/Adyen/adyen-react-native/pull/187)
2. call `start('paypal')`
3. close webview
4. loading overlay is not closed

**Expected behavior**
The loading with closed automatically like on IOS

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13

> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/1012532/231962847-ecd2766b-8506-46c9-8158-45444fe129f1.png">

**Comment by pinpong** [comment] 2023-04-25 11:10
Same problem with the official example.

**Comment by pinpong** [comment] 2023-04-26 08:10
After review the code the dialog is more a like a feature. Compared to DropinComponent we are not getting callback on `observeErrors`. @descorp any idea how to get a callback if the webview closed?
This is a show stopper for our app because it's not matching our ui implementation.

**Comment by descorp** [comment] 2023-04-26 08:56
Hey @pinpong 

> how to get a callback if the webview closed?

AFAIK, it is technically impossible - this is missing feature on Android. 
This was the main reason to introduce this "spinner overlay" in the first place.

> it's not matching our ui implementation.

Good new is it an Android - you can override any UI element by creating layout file with matching name in local `res` folder.
You are looking for [pending_payment.xml](https://github.com/Adyen/adyen-react-native/blob/develop/android/src/main/res/layout/pending_payment.xml)

**Comment by pinpong** [comment] 2023-04-26 14:53
see https://github.com/Adyen/adyen-android/issues/582

**Comment by pinpong** [comment] 2023-04-26 15:41
@descorp what do you think about [onTopResumedActivityChanged](https://developer.android.com/reference/android/app/Activity#onTopResumedActivityChanged(boolean))

**Comment by descorp** [comment] 2023-05-03 14:29
> what do you think about [onTopResumedActivityChanged](https://developer.android.com/reference/android/app/Activity#onTopResumedActivityChanged(boolean))

Well, it is not 100% reliable. Even from Google description:
```
In some cases it might be skipped and activity can go straight from `onResume()` to `onPause()` without receiving the top resumed state.
```

Also `onTopResumedActivityChanged` behavior could be misleading in case shopper decides to open an external browser and go back - `onTopResumedActivityChanged` will be called, but the payment is not necessary canceled.

**Comment by descorp** [comment] 2023-06-01 09:24
I am going to close this discussion with label **"Not a bug, but a feature"** 😄
Feel free to continue the discussion or reopen if needed.

**Closed as completed by descorp** 2023-06-01 09:24 UTC
Labels: bug report
