### ISSUE TITLE
Google Pay Not Visible 

### ISSUE THREAD

**Issue by vijay6162** [Adyen/adyen-react-native#294] opened 2023-10-19 09:55 UTC
**Describe the bug**
We are unable to see google pay payment method  even though we are getting response from payment methods.The main concern is  previously it used to work and its not visible right now even though nothing is changed from code prespective.

**To Reproduce**
Steps to reproduce the behavior :
1. Open DropIn
2. Observe that Google pay payment method is not visible

**Expected behavior**
     Google pay payment type should be visible

**Screenshots**
    ![WhatsApp Image 2023-10-19 at 3 18 55 PM](https://github.com/Adyen/adyen-react-native/assets/42997076/6c95b543-483d-43c6-a4fe-8b3dbcb37d4d)

**Smartphone (please complete the following information):**
 - Device: iOS 13
 - OS: macOs Monterey
 - Platform: React Native v0.67.5 [ Both Android & iOS ]
 - Adyen version:  @adyen/react-native : ^1.1.0
 - 
**Additional context**
Below are the payload details

Request sent to adyen
```json
{
  "merchantAccount": "TestLab_ECOM_DEV_TEST",
  "shopperLocale": "AU",
  "countryCode": "AU",
  "amount": {
    "currency": "AUD",
    "value": 1095 
  },
  "shopperReference": "57723887-8efe-4a76-af3d-6510d2ed6914",
  "allowedPaymentMethods": [
    "applepay",
    "scheme",
    "googlepay",
    "paypal"
  ],  
}
```
**Response received from adyen**
```json
{
  "paymentMethods": [
    {
      "brands": [
        "visa",
        "mc",
        "amex",
        "maestro"
      ],
      "name": "Credit Card",
      "type": "scheme"
    },
    {
      "configuration": {
        "merchantId": "GY89S727ZJ9E6",
        "intent": "capture"
      },
      "name": "PayPal",
      "type": "paypal"
    },
    {
      "configuration": {
        "merchantId": "000000000209726",
        "merchantName": "TestLab_ECOM"
      },
      "name": "Apple Pay",
      "type": "applepay"
    },
    {
      "configuration": {
        "merchantId": "50",
        "gatewayMerchantId": "TestLab_ECOM"
      },
      "name": "Google Pay",
      "type": "googlepay"
    }
  ]
}
```

**Comment by descorp** [comment] 2023-10-19 11:07
Hey @vijay6162 

Google Pay is not supported and is therefore ignored on iOS.
Is this the same on Android ?

**Comment by vijay6162** [comment] 2023-10-19 12:19
> Hey @vijay6162
> 
> Google Pay is not supported and is therefore ignored on iOS. Is this the same on Android ?

Yes, its not visible in android device as well

**Comment by descorp** [comment] 2023-10-19 13:46
Hey @vijay6162 

I can confirm that the json you shared above shows GooglePay on DropIn for me on Android device.
Make sure that emulator or device you are using have Google Services enabled.

---

I see both ApplePay and GooglePay in your `paymentMethods` JSON.
Make sure you passing [channel](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentMethods#request-channel) property correctly.

You can see example [here](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Configuration.js#L9-L12)

**Comment by vijay6162** [comment] 2023-10-20 01:54
Hi @descorp, I have rechecked and confirm that now i am able to load Google pay in dropin, But getting this authentication error.Let me know your suggestions.Thanks

https://github.com/Adyen/adyen-react-native/assets/42997076/c482ea6b-a949-4bc3-b758-b1a793d4664b

**Comment by descorp** [comment] 2023-10-20 09:27
Hey @vijay6162 

Check your Android Studio logs.
Also, make sure that [emulator or device you are using is compatible](https://developers.google.com/pay/api/web/guides/test-and-deploy/integration-checklist#test-on-compatible-device).
You can also try out GooglePay on https://www.mystoredemo.io/#/checkout in Chrome.

In general, I would advice you contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420).

**Comment by descorp** [comment] 2023-10-27 07:50
Since the original question was resolved, I am going to close this ticket.
Feel free to continue the discussion here

**Closed as completed by descorp** 2023-10-27 07:50 UTC
Labels: question
