### ISSUE TITLE
On Failure Listener Build is Crashing 

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#61] opened 2022-11-01 08:29 UTC
**Describe the bug**
When we open the dropIn(credit card) or any browser method(eg. paypal), and then we cancel the drop In(credit card) and any browser method(eg. paypal). It's give us error that Attempt to remove more AdyenDropIn listners than added.

**To Reproduce**
1. Open the dropIn
2. Go for payments 
3. Cancel the browser or dropIn method
![Simulator Screen Shot - iPhone 12 - 2022-11-01 at 13 13 57](https://user-images.githubusercontent.com/105792030/199189827-87cdc9f0-eef9-4441-bdcc-b0acb978c8c0.png)
error

**Expected behavior**
it should show this error

**Smartphone (please complete the following information):**

 - Version beta.6

**Comment by descorp** [comment] 2022-11-01 09:40
Hey @faizantariq1 

I am no able to reproduce it with example project within SDK or with a new RN project..
Are you using `AdyenCheckout` context ?

**Comment by iranaahsanali** [comment] 2022-11-01 11:03
We are using AdyenCheckout, see the same code.

```
<AdyenCheckout
      config={configuration}
      paymentMethods={paymentMethods}
      onSubmit={didSubmitCallback}
      onProvide={didProvideCallback}
      onFail={didFailCallback}
      onComplete={didCompleteCallback}>
      <CheckoutScreen
        navigation={navigation}
        route={route}
        isLoading={isLoading}
        amount={amount}
        paymentMethods={paymentMethods}
        isVisiblePaymentMethods={isVisiblePaymentMethods}
        setPaymentMethods={setPaymentMethods}
        onPressMethodSelect={onPressMethodSelect}
        showStorePaymentField={configuration.showStorePaymentField}
        initiatePaymentMethod={initiatePaymentMethod}
        paymentModalClose={paymentModalClose}
      />
    </AdyenCheckout>

```


The checkout Screen contains the UI code.

**Comment by descorp** [comment] 2022-11-02 09:23
@iranaahsanali 

Is this occurs on iOS, Android or both?

**Comment by iranaahsanali** [comment] 2022-11-02 09:31
Producible on iOS, Need to validate it on Android.

**Comment by descorp** [comment] 2022-11-04 10:54
Thanks for help @iranaahsanali 

The root cause is [this line](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenCheckoutContext.js#L76)
Will be fixed in beta-7 ASAP

**Comment by descorp** [comment] 2022-11-04 13:41
Fixed in #65

**Comment by descorp** [comment] 2022-11-04 16:57
Should be fixed in [Beta-7](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.7)

**Comment by descorp** [comment] 2022-11-16 17:26
Hey @iranaahsanali  @faizantariq1 

could you confirm if this bug fixed for you on BETA-7 ?

**Comment by descorp** [comment] 2022-11-29 10:57
@iranaahsanali @faizantariq1 
can you confirm?

**Comment by iranaahsanali** [comment] 2022-12-04 14:21
Working!!! Thanks

**Closed as completed** 2022-12-04 20:26 UTC
Labels: already fixed, bug
