### ISSUE TITLE
Example project does not compile - `FBReactNativeSpec.h:2216:46 'value' is unavailable: introduced in iOS 12.0`

### ISSUE THREAD

**Issue by dJani97** [Adyen/adyen-react-native#226] opened 2023-06-05 15:18 UTC
**Describe the bug**
The example project does not compile for iOS out of the box.

**To Reproduce**
- clone the project
- open the example folder
- open the ios folder in Xcode to change the Apple development team to our own
- run `yarn`
- run `yarn ios` or run the project from Xcode

**Screenshots**
![image](https://github.com/Adyen/adyen-react-native/assets/22769564/fffac854-ea80-4db9-bb00-6b3dc418ab88)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura (latest)
 - Hardware: Apple Silicon M1
 - Adyen project version: current develop branch ( #a1d144056cc540666f3d5b60910ea4be3d249925 )

**Smartphone (please complete the following information):**
 - Device: Tested on physical device "iPhone 7" and Simulator "iPhone 14"

**Comment by dJani97** [comment] 2023-06-05 15:21
I tried PR https://github.com/Adyen/adyen-react-native/pull/200 which changes the target iOS versions to `12.4`, but this doesn't seem to solve the problem.

**Comment by Gp2mv3** [comment] 2023-06-06 10:20
I can confirm this issue.
I tried to change the deployment target and the version in podFile but it doesn't help much.

**Comment by descorp** [comment] 2023-06-06 14:23
Workaround

Set 'React-Codegen' target version to iOS 12:
![Screenshot 2023-06-06 at 16 20 38](https://github.com/Adyen/adyen-react-native/assets/2648655/f0fd464f-62c9-4284-9f01-af23396bdf6f)

**Comment by descorp** [comment] 2023-06-07 15:13
Updating your "react-native" to "0.71.x" seems to be a solution.

**Comment by descorp** [comment] 2023-06-19 15:05
Released on [1.0.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0)

**Comment by descorp** [comment] 2023-06-21 10:02
I am going to close this thread for now.
Feel free to continue the discussion here or share your feedback.

**Closed as completed by descorp** 2023-06-21 10:02 UTC
Labels: already fixed
