### ISSUE TITLE
iOS import

### ISSUE THREAD

**Issue by BenSagir** [Adyen/adyen-react-native#122] opened 2023-01-19 13:48 UTC
**Describe the bug**
I am trying to integrate the Drop-In to my react-native project.
i could not build my app with the library added with yarn. 

in my project i have AppDelegate.mm and the importing way in the doc is not working in my project.

**Versions**
`"@adyen/react-native": "^1.0.0-beta.7"`
`"react-native": "0.68.0`
`"OS": "macOS 12.5.1"`
`"xcode": 14.1`

could you please help me? because right now if i dont add those lines to AppDelegate the is building but can't use the library..

**Comment by descorp** [comment] 2023-01-19 15:53
Hey @BenSagir 

This is duplicate of a problem #38

**Closed as completed by descorp** 2023-01-19 15:53 UTC
Labels: duplicate
