### ISSUE TITLE
New Architecture support

### ISSUE THREAD

**Issue by gunnartorfis** [Adyen/adyen-react-native#527] opened 2024-09-16 08:48 UTC
**Is your feature request related to a problem? Please describe.**
Currently @adyen/react-native crashes with the new architecture enabled even though the build succeeds. 

**Describe the solution you'd like**
It should be compatible with the new arch. 

**Additional context**
Here's a writeup from the React Working Group about what needs to be done to support the new arch: https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-libraries.md 

I'd be happy to contribute even though I don't have any experience with adopting the new arch.

**Comment by descorp** [comment] 2024-09-16 11:15
Hey @gunnartorfis 

Thanks for feedback 💚
New arch was on our backlog for a long time. Probably already too long 😅

We will start looking into it!

> @adyen/react-native crashes with the new architecture enabled 

Any particular steps to reproduce?
RN version ?

**Comment by gunnartorfis** [comment] 2024-09-16 11:17
It crashes as soon as I try to use AdyenCheckout for example but it might be just as soon as there's an import to adyen/react-native. 

I'm on 0.74.5 using Expo.

**Comment by descorp** [comment] 2024-09-16 15:14
@gunnartorfis 

How is your project configured / initiated ?
I have created new expo project (RN 0.74.5) with `npx create-expo-app --template blank` and [enabled](https://docs.expo.dev/guides/new-architecture/#enable-the-new-architecture-in-an-existing-project) new architecture:  it works for me on Android 🤔

**UPD**

iOS crashes for me on `getReturnURL:rejecter:` from `SessionHelper`
Do you receive simmilar crash ?

![Screenshot 2024-09-17 at 13 38 47](https://github.com/user-attachments/assets/ef169b12-f10e-443e-94eb-57708479bd22)


**UPD**

This crash was caused by missed declaration.
Fixed #529

**Comment by gunnartorfis** [comment] 2024-09-19 20:04
Hey @descorp

It was initialized 6 years ago 😅 , but is just an Expo app these days. 

That iOS crash looks like the one I got! Looking forward to see that merge released so I can test it out.

**Comment by descorp** [comment] 2024-10-01 15:00
Hey @gunnartorfis 

FYI, we have released [2.4.1](https://github.com/Adyen/adyen-react-native/releases/tag/2.4.1).

**Comment by camil-adyen** [comment] 2024-10-18 11:42
Closing this issue for now. Feel free to reopen if anything else needs to be addressed.

**Closed as completed by camil-adyen** 2024-10-18 11:42 UTC
Labels: enhancement
