### ISSUE TITLE
onAdditonalDetails callback not triggering in case of 3ds2 cards

### ISSUE THREAD

**Issue by vijay6162** [Adyen/adyen-react-native#298] opened 2023-10-27 04:23 UTC
**Describe the bug**
When we select credit card payment and enter 3DS2 card details, able to load challenge screen provided by dropIn and  when challenge submission is success its going back to the screen but "onAdditonalDetails"  callback is not being triggered.

This is observed in both Android & Ios.

**To Reproduce**
1. Load the Drop-in
2. Click on  credit card payment method and enter 3DS2 card details
3. Able to load challenge screen provided by dropin, Enter 1234 and click on submit 
4. Observe that onAdditonalDetails is not being triggered.

**Expected behavior**

onAdditonalDetails should trigger.

**Screenshots**
Please refer to request and response atttachments
[RequestRecived.json](https://github.com/Adyen/adyen-react-native/files/13184901/RequestRecived.json)
[RequestSent.json](https://github.com/Adyen/adyen-react-native/files/13184902/RequestSent.json)

https://github.com/Adyen/adyen-react-native/assets/42997076/99af63c2-1de3-4504-bd28-5b3a51ef8f45

**Smartphone (please complete the following information):**
 Device: iOS 13
 OS: macOs Monterey
 Platform: React Native v0.67.5 [ Both Android & iOS ]
 Adyen version: @adyen/react-native : ^1.1.0

**Comment by descorp** [comment] 2023-10-27 07:14
Hey @vijay6162 

I believe this is related to #295.
I am going to close it for now, if we find the root cause of #295 and the problem persists - we can always reopen it.

---

As a sanity check - make sure you provide a valid [`returnURL`](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#root-configurations).

**Closed as completed by descorp** 2023-10-27 07:14 UTC
Labels: bug report
