### ISSUE TITLE
Adyen latest sdk(2.3.0) Facing issue while opening paypal, ideal like any method that opening webview. can not read the property of undefined (reading AdyenInstant).

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#523] opened 2024-09-03 13:35 UTC
**Describe the bug**
facing a crash in Adyen latest sdk(2.3.0). while opening paypal, ideal etc.

**To Reproduce**
 const { start,paymentMethods: paymentMethodsResponse } = useAdyenCheckout();
 
 using start to directly open payment method like paypal
 
 start('paypal');
 
 it's giving error. can not read the property of undefined (reading AdyenInstant).
 
 
<img width="666" alt="Screenshot 2024-09-03 at 6 32 08 PM" src="https://github.com/user-attachments/assets/bcd0a0ed-a31d-4452-8fcf-c84501dfeb33">

it's crashing around line no 81 in the above screenshot.
 

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2024-09-03 at 18 26 56](https://github.com/user-attachments/assets/bc9122cc-dff6-4ff1-ad78-583df69ee05f)

![Simulator Screenshot - iPhone 15 Pro - 2024-09-03 at 14 19 15](https://github.com/user-attachments/assets/e3b2cad3-bfcb-4c3c-b608-374b456fcb8f)

**Smartphone (please complete the following information):**
 - Device: iphone simulator, android emulator

**Additional context**
react native: 0.69
compileSdkVersion = 34
targetSdkVersion = 34
java version = 17

**Note:**
I'm able to open the paypal when i use 
start('dropin')
and click on paypal.

**Comment by descorp** [comment] 2024-09-04 13:46
Thanks @faizantariq1 

I was able to reproduce - will look into this

**Comment by descorp** [comment] 2024-09-06 15:00
Hey @faizantariq1 

This is an issue for React Native versions before 73.
Our theory is module naming conflict: our file `NativeModules` got entangled with React Native `NativeModules` file.

To workaround: move "NativeModules" getters from `node_modules/@adyen/react-native/src/modules/NativeModules.tsx`  to  `node_modules/@adyen/react-native/src/wrappers/getNativeComponent.tsx`

```js
import { NativeModules } from 'react-native';
import { ModuleMock } from '../modules/NativeModules';

export const AdyenInstant: AdyenActionComponent & NativeModule = NativeModules.AdyenInstant ?? ModuleMock;
export const AdyenApplePay: AdyenComponent & NativeModule = NativeModules.AdyenApplePay ?? ModuleMock;
export const AdyenGooglePay: AdyenActionComponent & NativeModule = NativeModules.AdyenGooglePay ?? ModuleMock;
```

And remove unnecessary imports in `getNativeComponent.tsx`.

---

#524 
We will publish `2.4.0` with [backward compatibility PR](https://github.com/Adyen/adyen-react-native/pull/524) this next week.

**Comment by descorp** [comment] 2024-09-11 11:01
[2.4.0](https://github.com/Adyen/adyen-react-native/releases/tag/2.4.0) released.

@faizantariq1 could you verify if it fixed issue for you?

**Comment by faizan-tariq-lebara** [comment] 2024-09-12 12:01
Hi @descorp, the crash issue has been fixed. but while trying to open the ideal payment method is not working.

start('ideal');

but we did not receive any issuer(mean the issuer test payment methods screen) and onSubmit called automatically.  did something get changed? as it's working fine with the older version of adyen.
it's happening for both ios and android.

**Comment by faizan-tariq-lebara** [comment] 2024-09-12 13:30
Hi @descorp , 
One more thing, PayPal redirection is not working in Android after completing the payment or even after clicking on the cancel button. It was working fine in the previous version. 
![Screenshot_1726143798](https://github.com/user-attachments/assets/5f203c0e-a35d-4049-9007-490ab8e89ad6)
<img width="312" alt="Screenshot 2024-09-12 at 6 28 16 PM" src="https://github.com/user-attachments/assets/24ea5de5-e2e7-433d-b68c-0804e1aece28">

Note: it's working fine on IOS.

**Comment by descorp** [comment] 2024-09-12 14:45
Hey @faizantariq2 

## Ideal

>  did something get changed?

This is [a new thing](https://help.adyen.com/knowledge/payment-methods/ideal/what-is-ideal-2-0) indeed. Ideal is no longer an "issuer list", it is a simple redirect.

Our SDKs are dealing with this change differently. We are looking to introduce a more holistic solution for this.

> to open the ideal payment method is not working.

What is not working?


## PayPal redirection

Nothing have changes on this one 🤔

What `returnURL` you are using? 
For IDEAL and Cards (see a full list [here](https://github.com/Adyen/adyen-react-native/blob/develop/src/ComponentMap.ts#L81-L124)) it must be "adyencheckout://[YOUR_APP_BUNDLE]" - this value is coming from `data.returnUrl` inside of  `didSubmit(data, component)` callback.
For PayPal you must use any customURL that you set up with [intent-filter](https://developer.android.com/guide/topics/manifest/intent-filter-element) in `AndroidManifest`. 

The way we expect this to work:

You pass `returnUrl` in `AdyenCheckout` configuration and SDK rout your payment to a correct `returnUrl` by overriding it to  "adyencheckout://[YOUR_APP_BUNDLE]" or leaving untouched whenever nececery.

**Comment by faizan-tariq-lebara** [comment] 2024-09-12 15:54
### IDEAL:
**Note:** talking about sandbox environment.
const { start,paymentMethods: paymentMethodsResponse } = useAdyenCheckout();
start('ideal');
When I click on the button with start('ideal'), the onSubmit function is called automatically without displaying the issuer screen.


```
 ` const didSubmit = useCallback(
    async (
      /** @type {import('@adyen/react-native').PaymentMethodData} */ data,
      /** @type {import('@adyen/react-native').AdyenActionComponent} */ nativeComponent,
      /** @type any */ extra
    ) => {
      console.debug(
        `didSubmit: ${data.paymentMethod.type} with extra: ${JSON.stringify(
          extra,
          null,
          ' '
        )}`
      );
      try {
        /** @type {import('./../../Types/index').PaymentResponse} */
        const result = await ApiClient.payments(
          data,
          configuration,
          data.returnUrl
        );
        if (result.action) {
          nativeComponent.handle(result.action);
        } else {
          processResult(result, nativeComponent);
        }
      } catch (error) {
        processError(error, nativeComponent);
      }
    },
    [configuration]
  );`
```
. As a result, the data response does not include any issuer information, causing the payments API to fail.

**Comment by descorp** [comment] 2024-09-13 08:40
> When I click on the button with start('ideal'), the onSubmit function is called automatically without displaying the issuer screen.

This is expected behaviour for iDEAL 2.0.

> As a result, the data response does not include any issuer information, causing the payments API to fail.

This could be TEST environment configuration issue 🤔
What API version you have? 
Could you provide us with PSP reference via Support or Account Manager (we trying to avoid sharing PSP references via GitHub) ?

**Comment by camil-adyen** [comment] 2024-09-13 08:54
Hey @faizantariq2, due to the [new iDEAL 2.0](https://docs.adyen.com/payment-methods/ideal/ios-drop-in/#test-and-go-live) flow some changes were made to your payment methods setup in the Customer Area. Please enable the new ideal payment method confirgured to your test account and disable the old one to get the correct API response. 
<img width="825" alt="Screenshot 2024-09-13 at 10 53 34" src="https://github.com/user-attachments/assets/96447ae4-1a33-420f-a0b0-c4079e89ab27">

**Comment by camil-adyen** [comment] 2024-09-30 08:27
Hey @faizantariq2, can we close this issue?

**Closed as completed** 2024-10-18 11:41 UTC
Labels: already fixed, bug
