### ISSUE TITLE
Listener (onFail) not called on android when clicked on backbutton

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#196] opened 2023-04-26 10:10 UTC
**Describe the bug**

**To Reproduce**
-> Open drop in with ideal payment method
-> you are able to see banks
-> Click on android back button of device (not Listener called)
<img width="326" alt="Screenshot 2023-04-26 at 3 01 41 PM" src="https://user-images.githubusercontent.com/33232649/234543922-0033870d-5037-4210-afce-380c3802a848.png">

**Expected behavior**
Listener should be called so we can know that user close the banks screen.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android

**Additional context**

**Comment by descorp** [comment] 2023-04-26 11:27
Hey @faizantariq1 

on latest [1.0.0-rc.1](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-rc.1) `onFail` was marked as deprecated. 
Could you try using `onError` instead?

**Comment by pinpong** [comment] 2023-04-27 08:19
Can't reproduce this error. Working fine with the example.

**Comment by faizantariq1** [comment] 2023-05-09 11:20
Hi @descorp,
i have used 1.0.0-rc.2 package and also used onAdditionalDetails, onError.
but still on click of back button (android device) no listner is called.

**Comment by faizantariq1** [comment] 2023-05-09 11:21
@pinpong in android on click of back button any listner called on your side?

**Comment by faizantariq1** [comment] 2023-05-23 07:23
any update?

**Comment by descorp** [comment] 2023-05-23 15:46
@faizantariq1 

we can't reproduce this behaviour locally, so I can assume it is somehow effected by your setup.
Could you create a small demo app to reproduce the issue?

**Comment by faizantariq1** [comment] 2023-06-13 06:37
also able to produce on real device with version 1.0.0-rc.2.

**Comment by faizantariq1** [comment] 2023-06-16 15:03
This bug is fixed by:

Upgrade react from 0.64.2 to 0.66.5.
This code was missing in MainActivity, in onCreate, AdyenDropInComponent.setDropInLauncher(this);

**Comment by descorp** [comment] 2023-06-19 07:42
@faizantariq1 Thank you for verifying!

**Comment by descorp** [comment] 2023-06-19 15:08
I am going to close this thread for now. Feel free to continue discussion here.

**Closed as completed by descorp** 2023-06-19 15:08 UTC
Labels: bug report
